# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

strategy:
  matrix:
    linux2.7:
      imageName: 'ubuntu-16.04'
      python.arch: 'x64'
      python.version: '2.7'
    linux3.7:
      imageName: 'ubuntu-16.04'
      python.arch: 'x64'
      python.version: '3.7'
    mac2.7:
      imageName: 'macos-10.14'
      python.arch: 'x64'
      python.version: '2.7'
    mac3.7:
      imageName: 'macos-10.14'
      python.arch: 'x64'
      python.version: '3.7'
    windows2.7:
      imageName: 'vs2017-win2016'
      python.arch: 'x64'
      python.version: '2.7'
    windows3.7:
      imageName: 'vs2017-win2016'
      python.arch: 'x64'
      python.version: '3.7'
    windows32-2.7:
      imageName: 'VS2017-Win2016'
      python.arch: 'x86'
      python.version: '2.7'
    windows32-3.6:
      imageName: 'VS2017-Win2016'
      python.arch: 'x86'
      python.version: '3.6'
    windows32-3.7:
      imageName: 'VS2017-Win2016'
      python.arch: 'x86'
      python.version: '3.7'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    architecture: '$(python.arch)'
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)-${python.arch}'

- script: |
    pip install coverage
  displayName: 'Install coverage'

- script: |
    coverage run tests.py
  displayName: 'Run tests and collect coverage'

- script: |
    echo '$BUILD_SOURCEVERSION'
  displayNmae: 'Print sourceversion'

- script: |
    echo '$SYSTEM_PULLREQUEST_SOURCECOMMITID'
  displayNmae: 'Print pr source'

- script: |
    curl -s https://codecov.io/bash | bash
  displayName: 'Upload coverage reports to Codecov'
  env:
    CODECOV_TOKEN: $(CODECOV_TOKEN)
